
AOS.init({duration:600, once:true});
const swiper = new Swiper('.mySwiper', {slidesPerView:3,spaceBetween:16,loop:true,pagination:{el:'.swiper-pagination',clickable:true},navigation:{nextEl:'.swiper-button-next',prevEl:'.swiper-button-prev'},breakpoints:{320:{slidesPerView:1},640:{slidesPerView:2},980:{slidesPerView:3}}});
document.querySelectorAll('.swiper-slide img').forEach(img=>{img.addEventListener('click', ()=>{const lb=document.getElementById('lightbox');document.getElementById('lbimg').src=img.src;lb.style.display='flex';});});
document.getElementById('lightbox').addEventListener('click', ()=>{document.getElementById('lightbox').style.display='none';});
const SERVICES={hidden:{label:'Скрытый плинтус',price:60,anglesAllowed:true,doorsAllowed:true},hidden_light:{label:'Скрытый плинтус с подсветкой',price:90,anglesAllowed:true,doorsAllowed:true},shadow:{label:'Теневой плинтус',price:30,anglesAllowed:true,doorsAllowed:true},micro:{label:'Микро плинтус',price:6,anglesAllowed:true,doorsAllowed:true},micro_L:{label:'Микро L',price:8,anglesAllowed:true,doorsAllowed:true},duro:{label:'Дюрополимер',price:10,anglesAllowed:true,doorsAllowed:true},mdf:{label:'МДФ',price:10,anglesAllowed:true,doorsAllowed:true},pvc:{label:'ПВХ',price:8,anglesAllowed:true,doorsAllowed:true},wood:{label:'Дерево',price:12,anglesAllowed:true,doorsAllowed:true},metal:{label:'Металл',price:15,anglesAllowed:true,doorsAllowed:true},poly:{label:'Полиуретан',price:12,anglesAllowed:true,doorsAllowed:true},paint:{label:'Покраска',price:5,anglesAllowed:false,doorsAllowed:false},seal:{label:'Герметизация',price:3,anglesAllowed:false,doorsAllowed:false}};
const DEFAULT_COEFS={brick:1.15,monolit:1.20,plaster:1.10,gk:0.95,block:1.10,wood:1.00,radius:1.25};
function serviceOptionsHTML(){return Object.keys(SERVICES).map(k=>`<option value="${k}">${SERVICES[k].label} — ${SERVICES[k].price} руб/м</option>`).join('');}
function wallOptionsHTML(){const wallTypes=[{k:'brick',l:'Кирпичная'},{k:'monolit',l:'Монолитная'},{k:'plaster',l:'Штукатурка'},{k:'gk',l:'Гипсокартон'},{k:'block',l:'Блочная'},{k:'wood',l:'Деревянная'},{k:'radius',l:'Радиусная'}];return wallTypes.map(w=>`<option value="${w.k}">${w.l}</option>`).join('');}
let rowId=1;const calcBody=document.getElementById('calcBody');const addRowBtn=document.getElementById('addRowBtn');const grandTotalEl=document.getElementById('grandTotal');const sendWA=document.getElementById('sendWA');const copyBtn=document.getElementById('copyBtn');const clearBtn=document.getElementById('clearBtn');
function addRow(initial){const tr=document.createElement('tr');tr.dataset.id='r'+(rowId++);tr.innerHTML=`<td><select class="svc">${serviceOptionsHTML()}</select></td><td><input class="len" type="number" min="0" step="0.1" value="${initial?.len??0}"></td><td><input class="angles" type="number" min="0" step="1" value="${initial?.angles??0}"></td><td><input class="doors" type="number" min="0" step="1" value="${initial?.doors??0}"></td><td><select class="wall">${wallOptionsHTML()}</select></td><td style="text-align:right"><span class="rowTotal">0 руб</span></td><td style="text-align:center"><button class="removeBtn btn btn-ghost" style="padding:6px 8px">×</button></td>`;calcBody.appendChild(tr);const svc=tr.querySelector('.svc'),len=tr.querySelector('.len'),angles=tr.querySelector('.angles'),doors=tr.querySelector('.doors'),wall=tr.querySelector('.wall'),removeBtn=tr.querySelector('.removeBtn');svc.addEventListener('change',()=>{toggleFields(tr);updateRow(tr);updateTotal();});len.addEventListener('input',()=>{updateRow(tr);updateTotal();});angles.addEventListener('input',()=>{updateRow(tr);updateTotal();});doors.addEventListener('input',()=>{updateRow(tr);updateTotal();});wall.addEventListener('change',()=>{updateRow(tr);updateTotal();});removeBtn.addEventListener('click',()=>{tr.remove();updateTotal();});if(initial?.service)svc.value=initial.service;if(initial?.wall)wall.value=initial.wall;toggleFields(tr);updateRow(tr);updateTotal();return tr;}
function toggleFields(tr){const key=tr.querySelector('.svc').value;const cfg=SERVICES[key];const angles=tr.querySelector('.angles'),doors=tr.querySelector('.doors');if(cfg.anglesAllowed){angles.removeAttribute('disabled');angles.style.opacity=1;}else{angles.value=0;angles.setAttribute('disabled','disabled');angles.style.opacity=0.5;}if(cfg.doorsAllowed){doors.removeAttribute('disabled');doors.style.opacity=1;}else{doors.value=0;doors.setAttribute('disabled','disabled');doors.style.opacity=0.5;}}
function readCoefs(){const inputs=document.querySelectorAll('.coefInput');const obj={};inputs.forEach(i=>{obj[i.dataset.key]=parseFloat(i.value)||DEFAULT_COEFS[i.dataset.key]||1;});return obj;}
function updateRow(tr){const key=tr.querySelector('.svc').value;const len=parseFloat(tr.querySelector('.len').value)||0;const angles=parseInt(tr.querySelector('.angles').value)||0;const doors=parseInt(tr.querySelector('.doors').value)||0;const wallKey=tr.querySelector('.wall').value;const cfg=SERVICES[key];const base=cfg.price;const coefs=readCoefs();const wallCoef=coefs[wallKey]||1;const base_cost=base*len;const angle_cost=cfg.anglesAllowed?(base*angles):0;const door_cost=cfg.doorsAllowed?(base*doors):0;const adjusted_base=Math.round(base_cost*wallCoef*100)/100;let rowTotal=Math.round((adjusted_base+angle_cost+door_cost));tr.querySelector('.rowTotal').innerText=rowTotal+' руб';tr.dataset.calc=JSON.stringify({key,base,len,angles,doors,wallKey,wallCoef,adjusted_base,angle_cost,door_cost,rowTotal});return rowTotal;}
function updateTotal(){let sum=0;document.querySelectorAll('#calcBody tr').forEach(tr=>{const d=tr.dataset.calc?JSON.parse(tr.dataset.calc):null;if(d)sum+=Number(d.rowTotal);});grandTotalEl.innerText=Math.round(sum)+' руб';}
function buildReport(){const lines=[];document.querySelectorAll('#calcBody tr').forEach((tr,idx)=>{const d=tr.dataset.calc?JSON.parse(tr.dataset.calc):null; if(!d)return; const label=SERVICES[d.key].label; const basePart=Math.round(d.base*d.len); const anglePart=Math.round(d.base*d.angles); const doorPart=Math.round(d.base*d.doors); lines.push(`${idx+1}) ${label}: ${d.base} руб/м × ${d.len} м = ${basePart} руб; углы ${d.angles} шт = ${anglePart} руб; примыкания ${d.doors} шт = ${doorPart} руб; (коэф стены ${d.wallCoef}) → ${d.rowTotal} руб`);}); lines.push('Итого: '+document.getElementById('grandTotal').innerText); return lines.join('\n');}
function sendToWhatsApp(){const phone='375298274342';const report=buildReport();const name=encodeURIComponent('Здравствуйте! Хочу заказать монтаж плинтусов. Вот расчёт:%0A'+report);const url=`https://wa.me/${phone}?text=${name}`;window.open(url,'_blank');}
async function copyReport(){const txt=buildReport();try{await navigator.clipboard.writeText(txt);alert('Расчёт скопирован.');}catch(e){prompt('Скопируйте расчёт вручную:',txt);}}
function clearAll(){if(confirm('Очистить все позиции?')){calcBody.innerHTML='';addRow();updateTotal();}}
addRowBtn.addEventListener('click',()=>addRow());sendWA.addEventListener('click',sendToWhatsApp);copyBtn.addEventListener('click',copyReport);clearBtn.addEventListener('click',clearAll);addRow();document.querySelectorAll('.coefInput').forEach(inp=>inp.addEventListener('input',()=>{document.querySelectorAll('#calcBody tr').forEach(tr=>updateRow(tr));updateTotal();}));document.getElementById('sendLeadBtn').addEventListener('click',function(){const name=document.getElementById('clientName').value||'-';const phone=document.getElementById('clientPhone').value||'-';const comment=document.getElementById('clientComment').value||'-';const report=buildReport();const text=encodeURIComponent(`Здравствуйте! Заявка на монтаж плинтусов.%0AИмя: ${name}%0AТелефон: ${phone}%0AКомментарий: ${comment}%0AРасчёт:%0A${report}`);const url=`https://wa.me/375298274342?text=${text}`;window.open(url,'_blank');});
